server:
  port: 5050
  
  #$ git commit -m "added few classes"
#Author identity unknown

#*** Please tell me who you are.

#Run

 # git config --global user.email "k.munireddy91@gmail.com"
 # git config --global user.name "KavvamMunireddy" 

#to set your account's default identity.
#Omit --global to set the identity only in this repository.

#fatal: unable to auto-detect email address (got 'hp@DESKTOP-P4HEPG5.(none)')
  